[package]
name = "anonymous-credentials"
version = "0.1.0"
edition = "2021"
authors = ["Darnell Andries <dandries@brave.com>"]
description = "Implementation of Direct Anonymous Attestation for the Web Discovery Project"
license = "MPL-2.0"
repository = "https://github.com/brave-experiments/anonymous-credentials-rs"
keywords = ["daa", "credentials", "bn254"]
categories = ["cryptography"]

[dependencies]
lazy_static = "1.4"
rand = "0.8"
brave-miracl = { version = "0.1", features = ["std"] }
thiserror = "1.0"

[dev-dependencies]
hex = "0.4"
