[package]
name = "web-discovery-project"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.4"
rand = "0.8"
brave-miracl = { version = "0.1", features = ["std"] }
thiserror = "1.0"

[dev-dependencies]
hex = "0.4"
